version: '3'
services:
  api:
    image: r.patrick246.de/dhbw/ws-graphql:latest
    build: .
    ports:
      - "3001:3000"
    links:
      - "db:db"
  db:
    image: aashreys/mongo-auth:latest
    env_file:
      - mongo.env
    volumes:
      - "db-data:/data/db"
    ports:
      - 27017:27017
volumes:
  db-data: