version: '3'
services:
  api:
    image: r.patrick246.de/dhbw/ws-graphql:latest
    build: .
    ports:
      - "127.0.0.1:8082:3000"
    links:
      - "db:db"
    env_file:
      - .env
  db:
    image: aashreys/mongo-auth:latest
    env_file:
      - mongo.env
    volumes:
      - "db-data:/data/db"
volumes:
  db-data: