version: '3'
services:
  db:
    ports:
      - "27017:27017"
  db-admin:
    image: mongo-express
    links:
      - db:mongo
    ports:
      - "127.0.0.1:8089:8081"
  graphiql:
    image: vitalcode/auth-graphiql:master
    ports:
      - "127.0.0.1:8088:3000"